modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="buildermod"
version="0.1.5"
displayName="BuilderMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/black-steve0"
authors="black_steve0"
description='''
mod for builder
'''

[[dependencies.buildermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




